"""Days 1-10. Scene tuple: (section, narration_line, on_screen_text, visual_description, visual_spec).
Sections: H hook, E explanation, T takeaway, C cliffhanger.
Visual spec grammar: "pose/face/where ; prop:arg@slot ; ..." (see visuals.py)."""

DAYS = {}

DAYS[1] = dict(
    title="Why That Cringe Memory Never Leaves You",
    scenes=[
        ("H", "Why do you still cringe at that embarrassing moment?",
         "Still cringing", "Stickman clutches head, wincing, as a tiny cloud labeled 'that moment' hovers above.",
         "shock/worry/C; bubble:that moment@TR"),
        ("E", "When something embarrasses you, your body floods with stress hormones.",
         "Stress hormones flood in", "Stickman blushing with wavy red lines radiating from the body.",
         "stand/worry/L; waves@R; text:STRESS@TR"),
        ("E", "Your amygdala, a small emotion center deep in the brain, then tells your memory system: save this one.",
         "Amygdala: 'save this one'", "Cutaway brain with the amygdala highlighted in the accent color, stamping a SAVE tag.",
         "think/neutral/L; brain:amygdala@R; tag:SAVE@TR"),
        ("E", "Neuroscientist James McGaugh showed across decades of research that emotional arousal strengthens how memories get stored.",
         "Emotion = stronger memory", "Two bars: a short grey bar 'calm' and a tall accent bar 'emotional'.",
         "point/smile/L; bars:calm,emotional@R"),
        ("E", "Then you replay it again and again, which strengthens it even more.",
         "Replay, replay, replay", "A looping arrow circles a tiny stickman cringing.",
         "think/worry/L; loop@R"),
        ("E", "But vivid isn't the same as accurate. After 9/11, people felt certain about their memories, yet details drifted over time while confidence stayed high.",
         "Vivid is not accurate", "Two lines on a graph: 'confidence' stays flat and high, 'accuracy' slopes down.",
         "stand/neutral/L; lines:confidence,accuracy@R"),
        ("T", "Next time it replays, tell yourself: that's just my brain tagging it important, not proof anyone else remembers.",
         "Brain tagged it. That's all.", "Stickman calmly sticking a label 'important' on a thought cloud.",
         "point/smile/L; bubble:tagged@TR"),
        ("T", "Then shift your attention to something absorbing.",
         "Redirect your attention", "Stickman turns to a glowing book and puzzle piece.",
         "walk/smile/L; lightbulb@R"),
        ("C", "Tomorrow: the strange reason almost nobody noticed it in the first place.",
         "Tomorrow: who noticed?", "A crowd of tiny stickmen, all looking at their phones, none at our stickman.",
         "stand/neutral/L; crowd:5@R; text:TOMORROW@TR"),
    ],
    description="Why do cringe-worthy memories stick for years? Emotional arousal tells your brain to store an event more strongly, and replaying it locks it in even more. Source: McGaugh (2004), 'The amygdala modulates the consolidation of memories of emotionally arousing experiences', Annual Review of Neuroscience.",
    hashtags=["#psychology", "#shorts", "#memory", "#brain", "#mentalhealth", "#psychologyfacts"],
    accuracy_note="Flashbulb-memory finding (Talarico & Rubin, 2003): confidence in 9/11 memories stayed high while consistency of details declined, similar to everyday memories. Emotional memories feel vivid but are not necessarily more accurate. Simplified: the amygdala works with other regions (e.g. hippocampus), not alone.",
)

DAYS[2] = dict(
    title="Nobody Noticed Your Mistake (Here's the Proof)",
    scenes=[
        ("H", "Do you think everyone noticed that mistake?",
         "Did everyone notice?", "Stickman cowering under a harsh spotlight.",
         "shock/worry/C; spotlight@C"),
        ("E", "Psychologists call this the spotlight effect: feeling like you're on stage when you're actually in the audience.",
         "The spotlight effect", "Stickman alone under a spotlight, then the view zooms out to show an ordinary audience seat.",
         "stand/worry/L; spotlight@L; text:SPOTLIGHT EFFECT@TR"),
        ("E", "In 2000, Thomas Gilovich and colleagues had students wear an embarrassing Barry Manilow T-shirt into a room of other students.",
         "The embarrassing T-shirt study", "Stickman in a goofy T-shirt entering a room of tiny stickmen.",
         "walk/worry/L; tshirt:BARRY@R; crowd:4@B"),
        ("E", "The wearers guessed about half the people would notice it. Only around a quarter actually did.",
         "Guessed 50%. Actual: 25%", "Two bars: 'predicted ~50%' tall, 'noticed ~25%' short.",
         "point/neutral/L; bars:guessed=50%,actual=25%@R"),
        ("E", "Why? You're the star of your own experience, so your flaws feel huge. Everyone else is busy starring in theirs.",
         "Everyone's busy with their own show", "Crowd of stickmen each with a personal tiny spotlight over their own head.",
         "stand/smile/L; crowd:5@R"),
        ("E", "Your own embarrassment feels loud, but other people can't hear it.",
         "Loud to you. Silent to them.", "Speaker icon blaring beside the stickman while the crowd hears nothing.",
         "shrug/neutral/L; text:LOUD TO YOU@TR"),
        ("T", "Before your next big moment, ask: if I saw this happen to someone else, would I remember it tomorrow?",
         "Would you remember it?", "Stickman in thought, a thought bubble showing a stranger tripping.",
         "think/neutral/L; bubble:would I remember?@TR"),
        ("T", "Probably not. Then go ahead and take the stage.",
         "Probably not. Go.", "Stickman strides onto a stage confidently.",
         "walk/smile/L; spotlight@R"),
        ("C", "Tomorrow: the sneaky reason a price ending in nine feels so much cheaper.",
         "Tomorrow: $9.99", "A price tag reading $9.99 with a sly eye.",
         "stand/smile/L; tag:$9.99@R; text:TOMORROW@TR"),
    ],
    description="You probably think people noticed your slip-up far more than they did. Gilovich and colleagues found that people overestimate how much others notice them. Source: Gilovich, Medvec & Savitsky (2000), 'The spotlight effect in social judgment', Journal of Personality and Social Psychology.",
    hashtags=["#psychology", "#shorts", "#socialanxiety", "#psychologyfacts", "#confidence", "#brain"],
    accuracy_note="Figures are approximate: in the original study wearers estimated roughly 46% of observers would notice the shirt, versus roughly 23% who did. The effect has been replicated across several tasks, but sizes vary.",
)

DAYS[3] = dict(
    title="Why $9.99 Tricks Your Brain",
    scenes=[
        ("H", "Why does $9.99 feel so much cheaper?",
         "$9.99 vs $10", "Two price tags side by side: $9.99 and $10.00, one cent apart.",
         "stand/neutral/L; tag:$9.99@TR; tag:$10@R"),
        ("E", "It's called the left-digit effect. Your brain reads numbers left to right and anchors on the first digit.",
         "The left-digit effect", "Magnifying glass over the leftmost digit of $9.99.",
         "point/neutral/L; numbers:9 . 9 9@R"),
        ("E", "So $9.99 gets filed as 'about nine dollars' while $10 gets filed as 'ten dollars', even though the gap is one cent.",
         "'Nine-ish' vs 'Ten'", "Two mental drawers labeled 'nine dollars' and 'ten dollars'.",
         "think/neutral/L; bubble:nine-ish@TR; bubble:ten@R"),
        ("E", "Researchers Manoj Thomas and Vicki Morwitz found that the same price difference feels bigger when it changes the leftmost digit.",
         "Changing the digit feels bigger", "Arrow from $3.00 to $2.99 with a big jump drawn beneath it.",
         "point/smile/L; tag:$3.00@TR; arrow:right@R; tag:$2.99@B"),
        ("E", "Stores know this, which is why so many prices end in nine.",
         "Stores know this", "Rows of price tags all ending in 9.",
         "stand/smile/L; list:.99,.99,.99@R"),
        ("E", "The effect varies by product, and round prices can signal quality for premium brands.",
         "Premium brands use round prices", "A luxury watch with a round price tag.",
         "stand/neutral/L; coin:$500@R"),
        ("T", "So when you see a price ending in nine, mentally round up before deciding.",
         "Round the price up", "Stickman rounds $9.99 up to $10 with an eraser.",
         "point/smile/L; tag:$9.99@TR; arrow:right@R; tag:$10@B"),
        ("T", "Ask yourself: would I buy this at ten? You'll spot it everywhere.",
         "Would you pay $10?", "Thought bubble with a question mark over a price tag.",
         "think/neutral/L; qmark@R"),
        ("C", "Tomorrow: the reason your brain quietly ignores facts you disagree with.",
         "Tomorrow: facts you ignore", "A stickman with hands over his eyes in front of a fact sheet.",
         "stand/worry/L; list:FACT,FACT,FACT@R; text:TOMORROW@TR"),
    ],
    description="Why does $9.99 feel so much cheaper than $10? Your brain anchors on the leftmost digit, so a one-cent change can feel like a much bigger drop. Source: Thomas & Morwitz (2005), 'Penny wise and pound foolish: the left-digit effect in price cognition', Journal of Consumer Research.",
    hashtags=["#psychology", "#shorts", "#pricing", "#marketing", "#psychologyfacts", "#shopping"],
    accuracy_note="The left-digit effect is well documented, but its strength depends on the product and context. Premium or luxury brands often use round prices because round numbers can signal quality. Thomas & Morwitz also showed that the same price difference is judged larger when it changes the leftmost digit.",
)

DAYS[4] = dict(
    title="You're Not Seeing All the Evidence",
    scenes=[
        ("H", "You're not seeing all the evidence. Here's why.",
         "Not all the evidence", "Stickman wearing blinders staring at a big pile of papers.",
         "stand/neutral/C; list:YES,YES,NO@R"),
        ("E", "In 1960, psychologist Peter Wason gave people three numbers: 2, 4, 6. Their job was to guess the hidden rule.",
         "Wason's 2-4-6 puzzle", "Three big numbers 2 - 4 - 6 with a question mark rule box.",
         "point/neutral/L; numbers:2 4 6@R; qmark@TR"),
        ("E", "Many guessed 'add two each time,' then tested only numbers that fit, like 8, 10, 12. All of them got a yes.",
         "They tested what fit", "A row of green checkmarks next to 8, 10, 12.",
         "think/smile/L; numbers:8 10 12@R; check@TR"),
        ("E", "The real rule was simply any increasing numbers. Many people never tested something that could prove them wrong, like 5, 4, 3.",
         "Rule: any rising numbers", "Numbers 5, 4, 3 with a red cross, circled as untested.",
         "shock/neutral/L; numbers:5 4 3@R; cross@TR"),
        ("E", "That's confirmation bias: searching for, favoring, and remembering information that supports what you already believe.",
         "Confirmation bias", "Magnet pulling only 'agree' papers toward the stickman.",
         "point/neutral/L; magnet@R; text:CONFIRMATION BIAS@TR"),
        ("T", "Try this: before an important decision, ask 'what would prove me wrong?' Then actually go look for it.",
         "What would prove me wrong?", "Stickman holding a magnifying glass toward a 'NO' paper.",
         "think/smile/L; qmark@R; text:PROVE ME WRONG@TR"),
        ("T", "Sources that disagree with you aren't enemies. They're free error-checking.",
         "Disagreement = error-check", "A friendly red pen marking a paper with a tick.",
         "stand/smile/L; check@R"),
        ("C", "Tomorrow: why unfinished tasks keep nagging at the back of your mind.",
         "Tomorrow: unfinished tasks", "An open to-do list with half the items unchecked and glowing.",
         "stand/worry/L; list:TODO,TODO,TODO@R; text:TOMORROW@TR"),
    ],
    description="Confirmation bias means you naturally seek and favor information that matches what you already believe. Wason's classic 2-4-6 task shows how people test ideas in ways that can only confirm them. Source: Wason (1960), 'On the failure to eliminate hypotheses in a conceptual task', Quarterly Journal of Experimental Psychology.",
    hashtags=["#psychology", "#shorts", "#confirmationbias", "#cognitivebias", "#psychologyfacts", "#criticalthinking"],
    accuracy_note="Wason's task is a classic demonstration of seeking confirming evidence; it is a simplified model of real-world belief formation. Confirmation bias is robust but not absolute: people can be nudged to look for disconfirming evidence.",
)

DAYS[5] = dict(
    title="Why Unfinished Tasks Haunt Your Brain",
    scenes=[
        ("H", "Why can't you stop thinking about unfinished things?",
         "Why won't it let go?", "Stickman at a desk surrounded by half-done checklists.",
         "think/worry/C; list:TODO,TODO@R"),
        ("E", "It's called the Zeigarnik effect, named after psychologist Bluma Zeigarnik, who studied it in the 1920s.",
         "The Zeigarnik effect", "Vintage-style portrait frame with the name ZEIGARNIK.",
         "stand/neutral/L; text:ZEIGARNIK@R; text:1920s@TR"),
        ("E", "Her idea: interrupted tasks stick in memory better than finished ones. But later studies of that memory boost have had mixed results.",
         "Memory boost? Mixed results", "A scale tipping slightly, labeled 'mixed evidence'.",
         "shrug/neutral/L; scale@R"),
        ("E", "What does hold up is that unfinished goals keep intruding on your thoughts.",
         "Unfinished goals intrude", "Little thought bubbles with 'TODO' popping up above the stickman's head.",
         "think/worry/L; bubble:TODO@TR; bubble:TODO@R"),
        ("E", "Your brain keeps the loop open until there's a plan or an ending.",
         "The loop stays open", "A circular arrow with a gap, then closed.",
         "stand/neutral/L; loop@R"),
        ("E", "Researchers Masicampo and Baumeister found that making a specific plan for the task quiets those thoughts, even before you do it.",
         "A plan quiets the nagging", "Stickman writing a plan, the TODO bubbles fading away.",
         "point/smile/L; check@R; text:PLAN@TR"),
        ("T", "So don't just keep a to-do list. Write when and where you'll start.",
         "Write when and where", "Calendar and map pin icons next to a task.",
         "point/smile/L; clock@R; text:WHEN + WHERE@TR"),
        ("T", "'Tomorrow at nine, at my desk.' That tells your brain it's handled.",
         "'Tomorrow, 9am, my desk'", "Sticky note reading 9:00 desk with a check.",
         "stand/smile/L; tag:9:00 DESK@R; check@TR"),
        ("C", "Tomorrow: the surprising reason losing hurts more than winning feels good.",
         "Tomorrow: why losing stings", "Two coins: one gained, one lost, lost one bigger.",
         "stand/worry/L; coin:+$20@R; text:TOMORROW@TR"),
    ],
    description="Unfinished tasks can stay on your mind, but the details of the Zeigarnik effect are more nuanced than the popular story. Making a specific plan can quiet the mental nagging. Source: Masicampo & Baumeister (2011), 'Consider it done! Plan making can eliminate the cognitive effects of unfulfilled goals', Journal of Personality and Social Psychology.",
    hashtags=["#psychology", "#shorts", "#productivity", "#procrastination", "#psychologyfacts", "#brain"],
    accuracy_note="The original Zeigarnik memory advantage for interrupted tasks has had inconsistent replication; the safer claim is that unfinished goals intrude on thought and that specific plans reduce this intrusion (Masicampo & Baumeister, 2011). The popular 'waiter' origin story is anecdotal.",
)

DAYS[6] = dict(
    title="Why Losing Hurts More Than Winning Feels Good",
    scenes=[
        ("H", "Why does losing hurt more than winning feels good?",
         "Losing hurts more", "Stickman holding a lost coin, crying, beside a smaller won coin.",
         "shock/worry/C; coin:-$20@R"),
        ("E", "This is loss aversion, a core idea from Daniel Kahneman and Amos Tversky's prospect theory in 1979.",
         "Loss aversion", "Two portraits with the title PROSPECT THEORY 1979.",
         "stand/neutral/L; text:LOSS AVERSION@TR; text:1979@R"),
        ("E", "In experiments, many people turn down a coin flip where they could lose $100 unless they could win roughly $200.",
         "Lose $100? Need to win $200", "A coin flip with two sides: -$100 and +$200.",
         "think/neutral/L; coin:-$100@R; coin:+$200@B"),
        ("E", "Your brain puts a loss on the scale with extra weight.",
         "Losses weigh more", "A balance scale tipping toward the loss side.",
         "point/neutral/L; scale@R"),
        ("E", "One theory is that for our ancestors, losing food or shelter cost more than gaining extra helped.",
         "Why? Survival, maybe", "A cave with a few food items disappearing.",
         "stand/worry/L; text:SURVIVAL@R"),
        ("E", "Not every researcher agrees on how strong it is, though. Some argue it depends heavily on context and the stakes.",
         "Strength is debated", "Two stickmen arguing with a '?' between them.",
         "shrug/neutral/L; qmark@R; text:DEBATED@TR"),
        ("T", "To catch it, rewrite a decision as a gain instead of a loss and see if your answer changes.",
         "Flip loss into gain", "A card flips from 'lose $10' to 'keep $10'.",
         "point/smile/L; arrow:right@R"),
        ("T", "If it does, that's the bias talking.",
         "That's the bias talking", "A little devil speech bubble labeled 'bias'.",
         "stand/smile/L; bubble:bias@TR"),
        ("C", "Tomorrow: the famous psychology effect that you've almost certainly been misquoting.",
         "Tomorrow: a misquoted effect", "A quote bubble with a crossed-out sentence.",
         "stand/neutral/L; bubble:\"?\"@R; text:TOMORROW@TR"),
    ],
    description="Loss aversion is the idea that losses loom larger than equivalent gains. It's a cornerstone of behavioral economics, though researchers still debate how strong and universal it is. Source: Kahneman & Tversky (1979), 'Prospect theory: an analysis of decision under risk', Econometrica.",
    hashtags=["#psychology", "#shorts", "#lossaversion", "#behavioraleconomics", "#psychologyfacts", "#decisionmaking"],
    accuracy_note="'Roughly twice as large' is a common estimate (about 2 to 2.5 in Tversky & Kahneman, 1992), but some researchers (e.g. Gal & Rucker, 2018) argue loss aversion is overstated or context-dependent. The evolutionary explanation is a hypothesis, not established fact.",
)

DAYS[7] = dict(
    title="Dunning-Kruger: What Everyone Gets Wrong",
    scenes=[
        ("H", "Do clueless people really think they're geniuses?",
         "Do they think they're geniuses?", "Stickman wearing a paper crown looking proud.",
         "stand/smile/C; text:GENIUS?@R"),
        ("E", "In 1999, David Dunning and Justin Kruger tested people on logic, grammar, and humor.",
         "Dunning & Kruger, 1999", "Quiz sheets labeled LOGIC, GRAMMAR, HUMOR.",
         "point/neutral/L; list:LOGIC,GRAMMAR,HUMOR@R"),
        ("E", "Those who scored lowest still guessed they'd done better than average.",
         "Lowest scorers guessed 'above average'", "Two bars: low actual, higher guessed.",
         "stand/smile/L; bars:actual=25%,guessed=60%@R"),
        ("E", "The idea: the skills you need to do something well are the same skills you need to judge it.",
         "Doing and judging: same skill", "Two linked gears labeled DO and JUDGE.",
         "think/neutral/L; text:DO + JUDGE@R"),
        ("E", "Importantly, their finding was about specific skills, not general intelligence.",
         "Specific skills, not IQ", "Brain icon with a crossed-out 'IQ'.",
         "stand/neutral/L; brain:@R; cross@TR"),
        ("E", "But here's the catch. Some statisticians argue part of that famous pattern is a statistical artifact, and the popular 'Mount Stupid' graph isn't actually from the paper.",
         "The catch: it's debated", "A hill-shaped graph stamped 'NOT IN THE PAPER'.",
         "shrug/neutral/L; lines:myth,real@R; text:DEBATED@TR"),
        ("T", "So don't use it to label other people. Use it on yourself:",
         "Use it on yourself", "Stickman pointing a finger at his own chest.",
         "point/smile/L; qmark@R"),
        ("T", "when you're new at something, ask an experienced person to rate your work.",
         "Ask an expert to rate you", "Stickman handing a paper to a bigger, experienced stickman.",
         "stand/smile/L; crowd:1@R; check@TR"),
        ("C", "Tomorrow: why that annoying song is playing in your head right now.",
         "Tomorrow: your stuck song", "Musical notes floating from the stickman's head.",
         "stand/neutral/L; notes@R; text:TOMORROW@TR"),
    ],
    description="Do unskilled people really think they're geniuses? Not quite. Dunning and Kruger found that low performers on specific tasks overestimated their performance, but the popular version of the story is oversimplified. Source: Kruger & Dunning (1999), 'Unskilled and unaware of it', Journal of Personality and Social Psychology.",
    hashtags=["#psychology", "#shorts", "#dunningkruger", "#cognitivebias", "#psychologyfacts", "#selfawareness"],
    accuracy_note="Disputed/oversimplified: critics argue part of the classic pattern can arise from statistical effects (regression to the mean and the better-than-average effect). The popular 'Mount Stupid' curve does not appear in the original paper. The finding concerns specific skills, not general intelligence.",
)

DAYS[8] = dict(
    title="Why Songs Get Stuck in Your Head",
    scenes=[
        ("H", "Why is that song stuck in your head?",
         "Stuck song?", "Stickman holding head as musical notes swirl around it.",
         "shock/worry/C; notes@R"),
        ("E", "Scientists call it an earworm, and in one Finnish survey over ninety percent of people said they get one weekly.",
         "Earworms: 90%+ weekly", "A worm wearing headphones; a big '90%+' label.",
         "stand/neutral/L; notes@R; text:90%+@TR"),
        ("E", "Studies suggest earworms tend to be fairly fast, with simple, easy-to-sing melodies, often triggered by recent listening, stress, or a memory cue.",
         "Fast. Simple. Easy to sing.", "A checklist: fast tempo, simple melody, easy to sing.",
         "think/neutral/L; list:FAST,SIMPLE,CATCHY@R"),
        ("E", "Songs you've heard a lot recently are prime candidates.",
         "Recent songs loop more", "A calendar with a song icon highlighted this week.",
         "stand/smile/L; clock@R; notes@TR"),
        ("E", "Your brain's auditory and memory systems keep replaying the loop, even when you aren't trying.",
         "The loop replays itself", "Brain with a looping arrow around an ear.",
         "think/worry/L; brain:@R; loop@TR"),
        ("E", "Researchers still don't fully understand why some songs stick and others don't.",
         "Still a mystery why", "A shrugging stickman with question marks.",
         "shrug/neutral/L; qmark@R"),
        ("T", "One small experiment found that chewing gum reduced earworms, likely because it interferes with silently singing along.",
         "Try chewing gum", "Stickman chewing gum; the notes shrink.",
         "stand/smile/L; text:GUM@R; notes@TR"),
        ("T", "Engaging, moderately tricky puzzles may help too. Try both.",
         "Or a tricky puzzle", "Puzzle piece clicking into place.",
         "point/smile/L; lightbulb@R"),
        ("C", "Tomorrow: the sneaky first number stores show you, on purpose, before the real price.",
         "Tomorrow: the first number", "A big price tag crossed out with a smaller one.",
         "stand/smile/L; tag:$200@R; text:TOMORROW@TR"),
    ],
    description="Why do songs get stuck in your head? Earworms often follow recent exposure, stress, or memory triggers, and tend to be simple and repetitive. Source: Beaman, Powell & Rapley (2015), 'Want to block earworms from conscious awareness? B(u)y gum!', Quarterly Journal of Experimental Psychology.",
    hashtags=["#psychology", "#shorts", "#earworm", "#music", "#psychologyfacts", "#brain"],
    accuracy_note="The 90%+ weekly figure comes from a survey of Finnish adults (Liikkanen, 2012) and may not generalize. Song traits (fairly fast tempo, simple/common melodic shapes) follow Jakubowski et al. (2016). The chewing-gum finding comes from small lab experiments and shouldn't be treated as a guaranteed cure; the research on why particular songs become earworms is still developing.",
)

DAYS[9] = dict(
    title="The Pricing Trick Stores Use on You",
    scenes=[
        ("H", "Stores show you a number first. Here's why.",
         "The number they show first", "A big price tag looming over a tiny stickman.",
         "stand/worry/L; tag:$200@R"),
        ("E", "It's the anchoring effect. In 1974, Tversky and Kahneman had people watch a rigged wheel land on either 10 or 65.",
         "Tversky & Kahneman, 1974", "A wheel of fortune stopping on 10, then on 65.",
         "point/neutral/L; wheel:10@R"),
        ("E", "Then they asked: what percent of African countries are in the United Nations?",
         "A random number, then a question", "Question mark above a globe.",
         "think/neutral/L; qmark@R; text:% IN THE UN?@TR"),
        ("E", "People who saw 10 guessed around 25 percent. People who saw 65 guessed around 45.",
         "Saw 10: ~25%. Saw 65: ~45%", "Two bars: ~25% and ~45%, labeled by the wheel number.",
         "point/neutral/L; bars:saw 10=25%,saw 65=45%@R"),
        ("E", "A random number pulled the guesses. That's anchoring: your first number quietly shapes everything after it.",
         "First number pulls your guess", "Rope tied from a number to a thought bubble, pulling it.",
         "shock/neutral/L; text:ANCHOR@R"),
        ("E", "Stores use it with a high 'original price' next to the sale price so the deal feels bigger.",
         "'Was $200, now $120'", "Crossed-out $200 next to $120.",
         "stand/smile/L; tag:$200@TR; tag:$120@R"),
        ("T", "Before you shop or negotiate, decide your own number first. What's it worth to you? Then compare.",
         "Set your own number first", "Stickman writing a number on a sticky note before entering a store.",
         "point/smile/L; tag:MY #@R"),
        ("T", "In a negotiation, making the first offer often sets the anchor.",
         "Make the first offer", "Stickman planting a flag on a number line.",
         "walk/smile/L; arrow:right@R"),
        ("C", "Tomorrow: why walking through a doorway can make you forget everything.",
         "Tomorrow: doorways", "A doorway with a thought bubble vanishing through it.",
         "stand/neutral/L; door@R; text:TOMORROW@TR"),
    ],
    description="Anchoring means the first number you see quietly shapes your later judgments, which is why stores show a high original price. Source: Tversky & Kahneman (1974), 'Judgment under uncertainty: heuristics and biases', Science.",
    hashtags=["#psychology", "#shorts", "#anchoring", "#marketing", "#psychologyfacts", "#negotiation"],
    accuracy_note="Anchoring is one of the more robust effects in judgment research, though effect sizes vary by task. Figures are medians from the original wheel-of-fortune experiment (about 25% vs about 45%). Some later 'arbitrary anchor' studies (e.g. the Social Security number version) have had mixed replication, so we stick to the classic study.",
)

DAYS[10] = dict(
    title="Why You Forget Things Walking Into a Room",
    scenes=[
        ("H", "Why did you walk in here again?",
         "Why did I come in here?", "Stickman standing confused in a doorway with a blank thought bubble.",
         "shrug/worry/C; door@R"),
        ("E", "It's called the doorway effect, and it's real.",
         "The doorway effect", "A door with a glowing frame.",
         "point/smile/L; door@R"),
        ("E", "In 2011, Gabriel Radvansky and colleagues had people carry objects through virtual rooms, then tested their memory.",
         "Radvansky's virtual rooms, 2011", "A pixelated virtual room with a box being carried.",
         "walk/neutral/L; text:VIRTUAL ROOMS@R"),
        ("E", "People forgot more after passing through a doorway than after walking the same distance inside one room.",
         "More forgetting after doors", "Two paths: one through a door (more forgetting), one across a room (less).",
         "stand/neutral/L; bars:room,door@R"),
        ("E", "The leading explanation: your brain files experiences into 'events,' and a doorway marks a boundary, so the old thought gets filed away.",
         "Doors mark 'event boundaries'", "Thought bubble being packed into a box as the stickman steps through.",
         "think/neutral/L; door@R; bubble:old thought@TR"),
        ("E", "Researchers still debate the details, but it happens to healthy young brains too.",
         "Happens to healthy brains", "Smiling stickman with a healthy brain icon.",
         "stand/smile/L; brain:@R"),
        ("T", "So go back to the room where you had the thought. The scene itself often brings the memory back.",
         "Return to the original room", "Stickman walking back through the door; the thought bubble reappears.",
         "walk/smile/L; door@R; bubble:aha@TR"),
        ("T", "Or hold your goal in mind by repeating it before you move.",
         "Repeat your goal", "Stickman mouthing the goal word 'KEYS'.",
         "point/smile/L; text:KEYS@R"),
        ("C", "Tomorrow: why something you just learned suddenly seems to follow you everywhere.",
         "Tomorrow: it's everywhere", "Many identical objects popping up behind the stickman.",
         "stand/shock/L; crowd:5@R; text:TOMORROW@TR"),
    ],
    description="Walking through a doorway can make you forget why you entered the room. Researchers think doorways mark 'event boundaries' that make your brain file the old thought away. Source: Radvansky, Krawietz & Tamplin (2011), 'Walking through doorways causes forgetting', Quarterly Journal of Experimental Psychology.",
    hashtags=["#psychology", "#shorts", "#memory", "#doorwayeffect", "#psychologyfacts", "#brain"],
    accuracy_note="The doorway effect is documented in lab studies, but researchers still debate the exact mechanism (event boundaries vs. context change). Returning to the original room to restore context cues is supported by broader research on context-dependent memory, not just this study.",
)
